#%RAML 0.8
title: Produtos
version: 1.0
baseUri: http://localhost:8888

/products:
  displayName: Catálogo de Produtos
  get:
    responses:
      200:  
        body: 
          application/json:
            example: | 
              [{
                "id": 10,
                "name": "Coca-Cola",
                "price": 5
              },
              {
                "id": 11,
                "name": "Sprite",
                "price": 3
              },
              {
                "id": 12,
                "name": "Fanta",
                "price": 3
              }]
